-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.9.2
    hooks:
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-xml
    -   id: check-yaml
    -   id: debug-statements
    -   id: detect-private-key
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    -   id: file-contents-sorter
        files: .gitignore
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
-   repo: git://github.com/pre-commit/mirrors-pylint
    sha: v1.7.2
    hooks:
    -   id: pylint
        args:
        - -d fixme
        - -d import-error
        - -d invalid-name
        - -d locally-disabled
        - -d missing-docstring
        - -d W0406  # TODO: refactor server imports
        - -d cyclic-import  # TODO: refactor server imports
        - -d duplicate-code  # TODO: abstract view methods
-   repo: git://github.com/pre-commit/mirrors-eslint
    sha: v4.5.0
    hooks:
    -   id: eslint
-   repo: git://github.com/pre-commit/mirrors-fixmyjs
    sha: v2.0.0
    hooks:
    -   id: fixmyjs
-   repo: git://github.com/pre-commit/mirrors-jshint
    sha: v2.9.5
    hooks:
    -   id: jshint
-   repo: git://github.com/Lucas-C/pre-commit-hooks
    sha: v1.1.1
    hooks:
    -   id: remove-tabs
