version: '3.2'

services:
  client:
    build: client/
    ports:
      - "8080:4000"

  database:
    image: postgres:9.6.2-alpine
    ports:
      - "5432:5432"

  server:
    build: server/
    ports:
      - "8081:80"
