version: '3.2'

services:
  ysr_client:
    image: thekevjames/you-should-read-client:latest
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 20s
      update_config:
        parallelism: 1
        monitor: 20s

  ysr_server:
    image: thekevjames/you-should-read-server:latest
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 20s
      update_config:
        parallelism: 1
        monitor: 20s
    secrets:
      - database_url

secrets:
  database_url:
    external: true
