version: 2

jobs:
  check:
    docker:
      # https://github.com/docker-library/python/issues/155
      # - image: python:3.6.2-alpine3.6
      - image: python:3.6.2
    steps:
      - checkout
      - run: pip install pre-commit
      - run: pre-commit run --all-files

  server:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t server server/
      - deploy:
          name: push image (hash)
          command: |
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
            docker tag server "thekevjames/you-should-read-server:${CIRCLE_BRANCH}-${CIRCLE_SHA1:0:8}"
            docker push "thekevjames/you-should-read-server:${CIRCLE_BRANCH}-${CIRCLE_SHA1:0:8}"
      - deploy:
          name: push image (branch)
          command: |
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
            docker tag server "thekevjames/you-should-read-server:${CIRCLE_BRANCH}"
            docker push "thekevjames/you-should-read-server:${CIRCLE_BRANCH}"
      - deploy:
          name: push image (latest)
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
              docker tag server thekevjames/you-should-read-server:latest
              docker push thekevjames/you-should-read-server:latest
            fi

  server-deploy:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - run: apk add --no-cache curl
      - run:
          name: configure Heroku
          command: |
            mkdir -p /usr/local/lib
            curl https://cli-assets.heroku.com/branches/stable/heroku-linux-amd64.tar.gz | tar xz -C /usr/local/lib

            cat > ~/.netrc << EOF
            machine api.heroku.com
              login ${HEROKU_USER}
              password ${HEROKU_API_KEY}
            EOF
      - deploy:
          name: push image to heroku
          command: |
            cd server/
            /usr/local/lib/heroku/bin/heroku container:login
            /usr/local/lib/heroku/bin/heroku container:push --app you-should-read server

workflows:
  version: 2
  check-build-and-deploy:
    jobs:
      - check

      - server:
          context: org-global
          requires:
            - check

      - server-deploy:
          context: org-global
          filters:
            branches:
              only: master
          requires:
            - server
