version: 2

jobs:
  check:
    docker:
      # https://github.com/docker-library/python/issues/155
      # - image: python:3.6.2-alpine3.6
      - image: python:3.6.2
    steps:
      - checkout
      - run: python -m pip install pre-commit
      - run: pre-commit run --all-files

  docs:
    docker:
      - image: python:3.6.2-alpine3.6
    steps:
      - run: apk add --no-cache make
      - run: python -m pip install sphinx sphinxcontrib-napoleon
      - checkout
      - run: make -C docs html

  server:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t server server/
      - deploy:
          name: push image (hash)
          command: |
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
            docker tag server "thekevjames/you-should-read-server:${CIRCLE_BRANCH}-${CIRCLE_SHA1:0:8}"
            docker push "thekevjames/you-should-read-server:${CIRCLE_BRANCH}-${CIRCLE_SHA1:0:8}"
      - deploy:
          name: push image (branch)
          command: |
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
            docker tag server "thekevjames/you-should-read-server:${CIRCLE_BRANCH}"
            docker push "thekevjames/you-should-read-server:${CIRCLE_BRANCH}"
      - deploy:
          name: push image (latest)
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
              docker tag server thekevjames/you-should-read-server:latest
              docker push thekevjames/you-should-read-server:latest
            fi

  server-deploy:
    docker:
      - image: debian:stretch-slim
    steps:
      - run:
          name: install dependencies
          command: |
            apt-get update -qy
            apt-get install -qy apt-transport-https ca-certificates curl gnupg2 software-properties-common wget
            curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
            add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
            apt-get update -qy
            apt-get install -qy docker-ce
            wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
      - checkout
      - run:
          name: configure Heroku
          command: |
            cat > ~/.netrc << EOF
            machine api.heroku.com
              login ${HEROKU_USER}
              password ${HEROKU_API_KEY}
            EOF
      - setup_remote_docker
      # TODO: deploy as worker?
      - deploy:
          name: push image to Heroku
          command: |
            cd server/
            heroku container:login
            heroku container:push --app you-should-read web

  github-release:
    docker:
      - image: python:3.6.2-alpine3.6
    steps:
      - run: apk add --no-cache curl git openssh-client
      - checkout
      - run: curl -L https://github.com/aktau/github-release/releases/download/v0.7.2/linux-amd64-github-release.tar.bz2 | tar xj
      - run: curl -L https://github.com/clog-tool/clog-cli/releases/download/v0.9.3/clog-v0.9.3-x86_64-unknown-linux-musl.tar.gz | tar xz
      - deploy:
          name: create GitHub release
          command: |
            ./bin/linux/amd64/github-release release -t "${CIRCLE_TAG}" || true
            ./clog -F --setversion ${CIRCLE_TAG} | ./bin/linux/amd64/github-release edit -t ${CIRCLE_TAG} -d -

workflows:
  version: 2
  check-build-and-deploy:
    jobs:
      - check:
          filters:
            tags:
              only: /.*/
      - docs:
          filters:
            tags:
              only: /.*/

      - server:
          context: org-global
          filters:
            tags:
              only: /.*/
          requires:
            - check

      - server-deploy:
          context: org-global
          filters:
            branches:
              only: master
            tags:
              only: /.*/
          requires:
            - server

      - github-release:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
